### ISSUE TITLE
add help for GW

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#114]

**Comment by volodymyrss** [comment]
needs https://github.com/oda-hub/frontend-astrooda/issues/134

**Comment by motame** [comment]
#134 is now implemented !

**Comment by volodymyrss** [comment]
is this done, @dsavchenko , @andriineronov ?

**Comment by dsavchenko** [comment]
It's done in general, but we don't have the feedback from anyone (e.g. Eric). Of course, it could just mean that everything is fine there. 
And we also need to do the final check for incosistencies (the text on Renku button is changed, for example)

**Comment by volodymyrss** [comment]
Ok I leave it to discuss next time https://github.com/oda-hub/meetings/blob/main/2022-05-09

Is it possible for you to change the screenshot?

**Comment by dsavchenko** [comment]
> Is it possible for you to change the screenshot?

I have only unprivileged account on @motame's dev instance, so currently I can't change it directly

Of course, I can spawn another instance for this, but it's a bit of an effort

**Comment by volodymyrss** [comment]
> 

Don't you have your own instance already live?

**Comment by dsavchenko** [comment]
I don't currently have an instance automatically updated with some sort of CI/CD. The one I use for local development is not always up-to-date. So attention must be paid to update it manually to not introduce some incompatibility. Of course, if I move only help pages, the problems should not appear.

**Comment by volodymyrss** [comment]
We have to be aware of how much effort the update takes. Did you see the videos of Mohamed? I did not try, maybe it's hard.
I'd be kind of interesting if you managed to contribute to help pages, to check that it's not all locked in a single instance.

**Comment by dsavchenko** [comment]
OK, I will try
