### ISSUE TITLE
Add proper acknowledgement text for GW and DESI LegacySurvey

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/mmoda-frontend-module#122]
@andriineronov @volodymyrss @ferrigno your propositions?

**Comment by volodymyrss** [comment]
This is most of all up to @andriineronov , and should primarily contain the reference to GW sources. But, we might also add reference to the ODA paper - same as for INTEGRAL. What do you think @andriineronov ?

**Comment by dsavchenko** [comment]
Follow-up in https://github.com/oda-hub/mmoda-frontend-module/issues/137
