### ISSUE TITLE
Error reinstalling astrooda module

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/mmoda-frontend-module#124]
I was trying to reinstall the astrooda core module on my local installation.
I get the error `Error: Call to undefined function array_key_first() in astrooda_uninstall() (line 203 of /var/www/astrooda/sites/all/modules/astrooda/astrooda.install).`
Re-enabling afterwards kind-of-works, but the default values in common fields are lost and there are some warnings shown
```

    Notice: Undefined index: common in astrooda_name_resolve() (line 169 of /var/www/astrooda/sites/all/modules/astrooda/astrooda.common.inc).
    Notice: Undefined index: common in astrooda_common() (line 223 of /var/www/astrooda/sites/all/modules/astrooda/astrooda.common.inc).
    Notice: Undefined index: astrooda_debug in astrooda_main_block_content() (line 261 of /var/www/astrooda/sites/all/modules/astrooda/astrooda.module).
    Notice: Undefined index: help_page_nids in astrooda_main_block_content() (line 275 of /var/www/astrooda/sites/all/modules/astrooda/astrooda.module).
```

**Comment by motame** [comment]
I will have a look at it.

But if you want an immediate working instance, avoid to start from scratch.
Please use the 4 components:
- oda-hub/frontend-drupal7-for-astrooda (Drupal core + required modules)
- oda-hub/frontend-drupal7-db-for-astrooda (the database dump)
- oda-hub/frontend-astrooda (the Drupal module astrooda)
- oda-hub/frontend-bootstrap_astrooda (the used theme)

**Comment by dsavchenko** [comment]
Thanks
Of course, I start with all those components. But to test some changes in the modules, it's needed to reinstall them sometimes.

**Comment by volodymyrss** [comment]
I saw this (or sort of this) sometime too. For me it helped to follow a specific sequence. Uninstall all in a particular order, install back in the reverse order. Enable. I do not remember the exact sequence, please try

Starting fresh is the only safe way for now, it seems.

**Comment by dsavchenko** [comment]
This error occurred because of the old PHP in frontend-container. Gets eliminated with the transition to 7.3 https://github.com/oda-hub/frontend-container/commit/ba6b0cd81a0f81ae81e052016cb18f9ab5e0beaf
