### ISSUE TITLE
describe how to add new instument doc  (video?)

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#134]

**Comment by motame** [comment]
Two tutorial videos have been finally prepared and available on youtube :
1- [Presentation of the MMODA help book ](https://youtu.be/TZnnLsYz3Os)
2- [How to add/edit an MMODA help page](https://youtu.be/WYAP7uT38gI)

**Comment by volodymyrss** [comment]
Nice! Could we add the references in the readme here https://github.com/oda-hub/mmoda-frontend-module?

**Comment by volodymyrss** [comment]
could we add them please!

**Comment by volodymyrss** [comment]
@ferrigno will use them in #146

**Comment by ferrigno** [comment]
Added at https://github.com/oda-hub/mmoda-frontend-module#modify-help-pages
