### ISSUE TITLE
Add acknowledgement to LegacySurvey products

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/mmoda-frontend-module#137]
If this result is used for publicaiton, please include an acknowledgement of the Legacy Survey: https://www.legacysurvey.org/acknowledgment/

**Comment by volodymyrss** [comment]
> Yes, we can add "and MMMODA"?

With the reference to that INTEGRAL ODA paper?

**Comment by andriineronov** [comment]
.... well, that's not directly related... Is there a way to acknolwedge so that we can capture it to see how how often people use us in pulications?

**Comment by volodymyrss** [comment]
We could make a zenodo DOI record.
We could make it out of a github repo, which could contain some key references and details. We could start from this rather old readme: https://github.com/oda-hub/mmoda-manifesto 
I can improve, we review, and and make a DOI from it tomorrow.
