### ISSUE TITLE
ensure all images are visible

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#138]

**Comment by motame** [comment]
I tried a workaround for the time being by updating the help pages on the prod.
But can not, the directory sites/default/files seems not writable !
![o6VLbNIWaV](https://user-images.githubusercontent.com/44972498/160357532-6fde1935-d48f-4214-b31a-ec6a77e6d9ab.png)

**Comment by volodymyrss** [comment]
Ok I see the reason why they do not appear has to do with the php version in the container, I updated and it works - in staging.
