### ISSUE TITLE
Not latest version of the frontend code deployed

### ISSUE THREAD

**Issue by burnout87** [oda-hub/mmoda-frontend-module#139]

**Comment by burnout87** [comment]
I cannot load the page properly, is it correctly deployed?

**Comment by volodymyrss** [comment]
please provide details. which page? does it load incorrectly?

**Comment by burnout87** [comment]
I am using this [https://frontend-staging.obsuks1.unige.ch/mmoda/](https://frontend-staging.obsuks1.unige.ch/mmoda/)

And this is what I get:

![image](https://user-images.githubusercontent.com/3757833/159521455-c6008762-88f7-4d6c-b4c3-5ccc4575d884.png)

**Comment by volodymyrss** [comment]
check what happens in your case  - failure to load some resources - you can realize that they are fetched them from pre-defined place, configured per deployment.  Unclear why drupal does that. Maybe something should be changed to set deduce it dynamically.

the "reference" location is this one: frontend.staging.odahub.io/mmoda/
if you will login there, the other one will work too.

**Comment by burnout87** [comment]
Works now, did the login and the resources were loaded properly.

And I also can confirm that the version of the frontend is the latest one (checked with one renku-related test)
