### ISSUE TITLE
rearrange help book structure

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#161]
https://github.com/oda-hub/mmoda-frontend-module/issues/158

**Comment by volodymyrss** [comment]
in the future, we will use https://github.com/oda-hub/mmoda-frontend-module/issues/162

**Comment by burnout87** [comment]
Updates have been performed on the dev-instance.

**Comment by volodymyrss** [comment]
have they been committed to the module code?

**Comment by motame** [comment]
Before pushing it to github, I had a look there and the page "INTEGRAL mission" needs probably to be updated.
There is a reference there to Polar and ANTARES.
The two points need to be probably deleted from the list:
![BKzJ308loz](https://user-images.githubusercontent.com/44972498/170945944-af69065d-f5fc-49a0-84a3-991c061f0482.png)

@ferrigno, I delete the two lines or not ?

**Comment by motame** [comment]
If validated by Carlo, it will be delete then committed again.

**Comment by ferrigno** [comment]
I have revised the MMODA main page and others. It is OK for me, now.
