### ISSUE TITLE
make virtual module for INTEGRAL, to store help pages

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#162]

**Comment by volodymyrss** [comment]
if dev instance is used to make contributions to help pages (as it is primarily done now), this issue blocks https://github.com/oda-hub/mmoda-frontend-module/issues/161

this situation shows some disadvantage of using the same dev instance of @motame for help page update: the help pages are updated by various people, but they must be committed by @motame 

in principle, following successful help page update by @dsavchenko in https://github.com/oda-hub/mmoda-frontend-module/pull/157 we know that an update to help pages can be done from another instance.

There is not, however, right now an instance which would enable @ferrigno to make this update.

* in the future, we can make an instance just for help pages updates. it's easy to do in the k8s, 1h of my activity
* for now, we could wait until this #162 issue here is closed. unless it takes too long - then revert to option above.

**Comment by motame** [comment]
The concept of virtual instrument has been implemented.
A virtual instrument means simply that the instrument does not show up as an instrument for which it is possible to request data products via a dedicated form. It is there just to have a set of help pages attached to it.
The module dependency is taken into account, for instance the three instruments "INTEGRAL ISGRI", "INTEGRAL JEMX" and "INTEGRAL SPI ACS" depend on the virtual instrument "INTEGRAL". This means that all general help pages of "INTEGRAL" should be installed before specific instruments can be installed.

It's implemented by a flag (virtual) within the instrument settings, if set and its value is TRUE, the instrument is then said to be virtual and the system do not try to show up its tab on the main window.
![XWin_loDLt99tMF](https://user-images.githubusercontent.com/44972498/170056213-9f78753a-5043-41ae-9fe4-9f3b60299f9c.png)
