### ISSUE TITLE
Improve Renkulab error message for non-logged users

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/mmoda-frontend-module#180]
If a user is not logged in, when clicking on "View on Renku"

The message is 

Error while publishing to the Renku repository:
A token must be provided.

It should be something like 
Error while publishing to the Renku repository: please login to MMODA first and then retry.

A user did not understand the meaning of the message.

**Comment by burnout87** [comment]
What do you think ? @ferrigno @volodymyrss @motame 

![image](https://user-images.githubusercontent.com/3757833/187390565-edecebbc-ad09-40dc-8ff1-c81459664ac2.png)

**Comment by ferrigno** [comment]
looks good !
