### ISSUE TITLE
Login and Sign-Up not properly loaded

### ISSUE THREAD

**Issue by burnout87** [oda-hub/mmoda-frontend-module#185]
I have been reported the following behavior when try to sign-up as well as login. Any ideas on what it could be?

![image](https://user-images.githubusercontent.com/3757833/200516204-e735dbd2-ea4f-4704-9fc1-80e68c3ce188.png)

**Comment by motame** [comment]
Tested right now on different browsers and I had indeed an error with Firefox while it is OK with Chrome, Edge and Opera.
On which browser please ?

However the error message is different ! See attached screenshot.
It does not load a JS script related to EU cookie compliance module then of course it does not find a function $.cookie !!!
https://cdcidev.mtmco.net/mmoda/sites/all/modules/eu_cookie_compliance/js/jquery.cookie-1.4.1.min.js?v=1.4.1

![oAiPGweYsn](https://user-images.githubusercontent.com/44972498/200771075-7be140dc-d471-4687-840b-9e912031d32b.png)

**Comment by motame** [comment]
The error disappears by cleaning the cache but it's still annoying !
https://www.drupal.org/project/eu_cookie_compliance/issues/3056808

**Comment by burnout87** [comment]
> Tested right now on different browsers and I had indeed an error with Firefox while it is OK with Chrome, Edge and Opera. On which browser please ?
> 

It happened to hubert, after trying both on his chrome and his firefox. I also made the same test on my personal laptop at home (Chrome) and got another different error, that seems to be related to the registration form itself:

![image](https://user-images.githubusercontent.com/3757833/200773092-6d06a13f-851b-4413-9515-dd2c08de2476.png)

**Comment by motame** [comment]
OK !
I found the reason for the issue I mentioned above !
[Only on Firefox "Loading failed for the <script> with source"](https://stackoverflow.com/questions/45879671/only-on-firefox-loading-failed-for-the-script-with-source)

It's a Firefox extension which is blocking the loading of the script : 
[Ghostery](https://addons.mozilla.org/en-US/firefox/addon/ghostery/) !
It may be also AdBlock ! (ads blockers in general).

I'll try now to fix the issue you reported, Gabriele: Uncaught Error: The callback URL is not local and not trusted !

**Comment by motame** [comment]
It's finally fixed !
The error is related to a contrib module: Modal forms.
It allows opening pages in modal windows.

It does not reconstruct properly the URL of the AJAX call.
`https://cdcidev.mtmco.net/modal_forms/ajax/login`
instead of
`https://cdcidev.mtmco.net/mmoda/modal_forms/ajax/login`
ignoring the base path !! (the prefix /mmoda/)

**Comment by motame** [comment]
Pushed to github !
Voldymyr, for a hot fix on the prod, you can install only the component [mmoda-frontend-theme](https://github.com/oda-hub/mmoda-frontend-theme)

**Comment by burnout87** [comment]
This was fixed, can be closed. To re-open if needed
