### ISSUE TITLE
figure out and explain how to restrict some tabs to "developers" role

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#187]

**Comment by motame** [comment]
This feature is implemented via a setting parameter initialized at module install.
The parameter is called roles_only.
If not specified in the module file mmoda_XXXX.install it means that there is no restriction on the module/instrument.
The tab is displayed to everybody. It means that nothing changes for the existing instruments (appear to all).
 
If the parameter is specified, it should contain a comma separated list of roles allowed to view the instrument.
Only users having those roles will see the tab !
And of course if the list is empty, the tab will never show-up whatever user is !!!
This feature is implemented and pushed in Github.

**Comment by volodymyrss** [comment]
thank you @motame !

**Comment by volodymyrss** [comment]
I think @dsavchenko should confirm to see how it works

**Comment by dsavchenko** [comment]
Is there an easy way to reset these restrictions for the previously installed instrument? 
When I checked this before, it seems it is stored somewhere in db and preserved even after instrument reinstallation and cache cleaning. So I was unable to allow the restricted instrument to anyone afterward. That was the reason I did #190

**Comment by motame** [comment]
The requested restriction can be achieved via the roles (define a role Developer).
It is achieved by the parameter allowed_roles. If it contains only "Developer", the access is restricted to users having the role "Developer".
See comment in issue [#190 ](https://github.com/oda-hub/mmoda-frontend-module/pull/190#issuecomment-1408236878)

**Comment by volodymyrss** [comment]
@dsavchenko please check and close
