### ISSUE TITLE
make an iframe (or so) view of the gallery upon "explore" button click

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#194]

**Comment by motame** [comment]
For this first prototype, the MMODA gallery is considered as any other instrument.
A dedicated module is created MMODA Gallery (mmoda_gallery under instruments).
The form has one field, product type and the result is displayed as an iframe within a panel as any other result.

All the machinery is implemented for a demo but the MMODA gallery is not allowing integration in iframe (CORS issue).
MMODA Gallery should allow iframe from https://cdcidev.mtmco.net.
`
X-Frame-Options: allow-from https://cdcidev.mtmco.net/
`
See screenshots.

![aC5TjUxHhS](https://user-images.githubusercontent.com/44972498/235479056-5c99e68e-9b4b-4054-b4f3-bc2b5442276d.png)


![A2TwuhqWM1](https://user-images.githubusercontent.com/44972498/235479131-b4a2ce2f-584c-4f9c-b8f4-0e5b99cd7aaf.png)

**Comment by motame** [comment]
There are in fact few ways to fix this issue.
I tried the one using proxypass (avoid CORS issue !).
Instead of requesting the product https://cdciweb02.isdc.unige.ch/mmoda/galleryd/node/5694/preview
I created a proxypass : `ProxyPass /mmoda/galleryd/   http://cdciweb02.isdc.unige.ch/mmoda/galleryd/`

Then I put the url https://cdcidev.mtmco.net/mmoda/galleryd/node/5694/preview in the iframe src.
And of course it works. You can try it on https://cdcidev.mtmco.net/mmoda

**Comment by burnout87** [comment]
I did some research and found a module that addresses this specific purpose: [https://www.drupal.org/project/allow_iframed_site](allow_iframed_site).

I just tried and it works, as you can see the ` X-Frame-Options` header is no longer, just for previews:

![image](https://user-images.githubusercontent.com/3757833/235635315-193ef9bb-9a08-42e4-a7cd-b128e379e095.png)

Whereas it still is for the other pages:

![image](https://user-images.githubusercontent.com/3757833/235635606-45f482dc-e1bc-48bf-a06c-c09956ba5f31.png)

**Comment by burnout87** [comment]
> I did some research and found a module that addresses this specific purpose: [allow_iframed_site](https://www.drupal.org/project/allow_iframed_site).
> 

Removed this external module, and extended our internal `mmoda_gallery` module with an event subscriber that remove the `X-Frame-Options` only in case a preview is requested.

Also, currently modern browsers no longer support `ALLOW-FROM origin`, as this is deprecated, so only `SAMEORIGIN` and `DENY` are accepted [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options](MDN)

**Comment by burnout87** [comment]
Issuing the github sign-in request for the gallery, from the iframe in mmoda, results in github blocking this for security reasons. 

At this point we will not explore further options (like SSO), but will maintain the double github singing-in process as it has been developed until now. We will instead focus the intention on the drupal migration from 7 to 9. Once the migration is complete,  perhaps this integration will become easier given the matching drupal versions.

**Comment by volodymyrss** [comment]
> At this point we will not explore further options (like SSO)

What do you mean? login-with-github is SSO.
