### ISSUE TITLE
make euclid filter selection UI: mutliple composed fields

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#197]
@dsavchenko

for https://renkulab.io/gitlab/astronomy/mmoda/photoz-euclid

**Comment by volodymyrss** [comment]
we were meant to track the issue in here, but some sketches, documents, and other information were only sent by email unfortunately.
We'll try to store all here.

for the record, the project for which it is needed is this one https://gitlab.renkulab.io/astronomy/mmoda/photoz-euclid/

**Comment by matucci72** [comment]
Here the presentation I showed
<img width="1015" alt="Screenshot 2023-10-03 at 16 40 29" src="https://github.com/oda-hub/mmoda-frontend-module/assets/135035124/c7ff51c1-d8d1-47db-a67c-d4117958f7c2">

**Comment by motame** [comment]
Oups ! Marco, may be copy/paste effect ... the same value in all rows :-)

**Comment by motame** [comment]
> This is the list for the first column "Filter":
> 
> CFHT/MegaCam.g CFHT/MegaCam.g CFHT/MegaCam.g CFHT/MegaCam.g CFHT/MegaCam.g

Oups ! Marco, may be copy/paste effect ... the same value in all rows :-)

**Comment by motame** [comment]
I fully agree with your suggestion !
It simplifies users life :-). Instead of a long instrument/filter list, the user will select first an instrument then only the corresponding filers are shown.

**Comment by motame** [comment]
The feature is implemented and can be tried on https://cdcidev.mtmco.net/mmoda/

A "fake" instrument is created : mmoda_euclid.
The list of filters is taken from a csv file  [euclid_filters.csv](https://github.com/oda-hub/mmoda-frontend-module/files/12843920/euclid_filters.csv)  provided in the root directory of the instrument (a CSV format is better than a free text file).

**Comment by volodymyrss** [comment]
sorry I do not see it, I am looking incorrectly probably

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/7236d836-4403-4523-bbaa-0589835a77fa)

**Comment by motame** [comment]
Bottom of the query parameters panel, just before submit !

**Comment by motame** [comment]
Sorry ! the first instrument !

**Comment by motame** [comment]
The corresponding parameters are sent (POST) to the server as three vectors : filter[], flux[] and flux_error[]

**Comment by volodymyrss** [comment]
> Sorry ! the first instrument ! It's a copy of INTEGRAL isgri. Do not pay attention to the other parameters .. :)

yeah sorry I did not look close enough. Looks good I guess, but it's really up to @matucci72 to see how this works for him!

**Comment by volodymyrss** [comment]
> The feature is implemented in a new branch (euclid-filter-select-ui) and can be tried on https://cdcidev.mtmco.net/mmoda/
> 
> A "fake" instrument is created ( a copy of INTEGRAL isgri) : mmoda_euclid. The list of filters is taken from a csv file [euclid_filters.csv](https://github.com/oda-hub/mmoda-frontend-module/files/12843920/euclid_filters.csv) provided in the root directory of the instrument (a CSV format is better than a free text file). The filters are saved in the database with the instrument configuration during the module installation. Marco, the two columns are grouped using the HTML tag optgroup for "option group". This seems to me better for user experience (one selection instead of two). The corresponding parameters are sent (POST) to the server as three vectors : filter[], flux[] and flux_error[]

This part needs to be figured out with @dsavchenko to see how it matches annotations we need to create in the notebook. we can discuss tomorrow after the meeting? or even later today?

**Comment by dsavchenko** [comment]
I'm flexible in time this days, so fix the meeting whenever you want

**Comment by dsavchenko** [comment]
@motame I don't see the instrument folder in the branch https://github.com/oda-hub/mmoda-frontend-module/tree/euclid-filter-select-ui seems

**Comment by volodymyrss** [comment]
> I'm flexible in time this days, so fix the meeting whenever you want

ok, lets discuss tomorrow, today is getting tricky already

**Comment by volodymyrss** [comment]
some validation might be needed

**Comment by volodymyrss** [comment]
frontend validation should prevent empty fields, both is drop-down list and in column name fields

**Comment by volodymyrss** [comment]
this issue will conclude in the JS librariry push

**Comment by motame** [comment]
The GUI as well as its validation are done following our discussion of 18.10.2023 14h.
There are some issues with the used JS JQuery library (bootstrapValidator) for the form validation in MMODA. It doesn't handle properly multivalued fields. When validating a form, it does not return proper events, neither success, neither error ! in addition to bad color rendering when an error is shown around a specific field (error message is shown in a green color !).
After struggling a bit, I found workarounds and the form is now working properly. You can test it:
https://cdcidev.mtmco.net/mmoda/

The concept of multivalued field is provided by the MMODA core via JQuery JS.
All is needed is to attach a CSS class to the container of the mulitvalued field and another one to the composed field  (the structure to be repeated).
Regarding the automatic generation of the forms (generated tab) I am wondering how to implement that ! as for now the validation is hard-coded : a JS JQuery code. A JQuery code need to be generated too.
Note that the version of the bootstrapValidator library is too old (Bootstrap 3).
When moving to Drupal 10, Bootstrap 5 will be used and I hope those issues are no more there.

**Comment by motame** [comment]
I will do some clean-up and push it soon to GitHub.

**Comment by motame** [comment]
Pushed in GitHub (branch euclid-filter-select-ui).

**Comment by dsavchenko** [comment]
I used the branch as an example to add the functionality to the tab generator and then cleaned-up the example instrument to make a PR https://github.com/oda-hub/mmoda-frontend-module/pull/228 with the required js changes

**Comment by matucci72** [comment]
@motame Hi Mohamed, I have a new (quite long) list of new filters for the Photoz-Euclid project. Could you please add them to the previous list, so users can select them from the MMODA page. I attach below the list. Please, note that the "Subaru" instrument is already present, so they should be together with the existing ones. Moreover, could you remove from the previous list the filters WISE W3 and W4, because I have problems with them... Thanks

[filters_list_new.txt](https://github.com/user-attachments/files/18092095/filters_list_new.txt)

**Comment by dsavchenko** [comment]
Hi @matucci72 this is on me, the list of filters is currently hardcoded in the dispatcher code. Either need to be changed there or we need to invent a way to pass this kind of metadata from backend to frontend. 
I will open an issue in dispatcher repo
