### ISSUE TITLE
"unknown instrument" for lightcurve in the LST1 panel (Image and Spectrum work Ok)

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/mmoda-frontend-module#202]
I am testing LST1 service, made Image, Spectrum and Lightcurve, using more-or-less identical approach...... When deployed, the service for Image and Spectrum work, but for the lightcurve a surprising message that "lst1" isntrument is not known appears (this is on staging.odahub.fr):

<img width="843" alt="image" src="https://github.com/oda-hub/mmoda-frontend-module/assets/27765790/2f585797-4955-49df-a1ca-37614556d9ff">

**Comment by dsavchenko** [comment]
This is temporary issue that could occur due to some problems connecting backend when trying to get backend options. Will be resolved with https://github.com/oda-hub/dispatcher-plugin-nb2workflow/issues/71 so I close this one
