### ISSUE TITLE
make it possible to import markdown or html into help page

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#204]
example of html attached converted from https://gitlab.renkulab.io/astronomy/mmoda/fermi/-/blob/master/Help.md

so that the bot can use it, see https://github.com/oda-hub/oda-bot/issues/24

@dsavchenko will attach

**Comment by dsavchenko** [comment]
@motame 
Here is an example html after conversion. 
There is a style referenced, used by katex (only css and no js needed to render latex with it). This can be turned off, if we opt to include it generally in the theme's head (but then we will need to fix the version of katex used).

[fermi_help_example.html.gz](https://github.com/oda-hub/mmoda-frontend-module/files/12538056/fermi_help_example.html.gz)

**Comment by motame** [comment]
The import of HTML files is implemented.
The module installer will look for them in the directory help_book of the instrument module.
The installer checks that the content of the directory help_book is php files or html files but not both.
If both types of files are found, it won't import neither of them.
php files correspond to the current situation where the help pages are saved as a node exports.
They are in fact the help pages created via the MMODA GUI while the html files are provided by a tier source as help pages (such as the generated tabs)
All files *.html will be imported as help pages (content type : MMODA Help Page).
The title is the same for all : the name of the instrument as defined in config of the instrument.
In a future version, the title can be extracted from the html file (after agreeing on the corresponding tag: H1 for instance !)
Regarding the help book table of contents (TOC), the installer will add them at the end.
It looks in fact for the page of the root pages of the book having the highest weight and increment it by 5 !
This can be changed in the future by another function.

In the same way, those help pages (nodes) are deleted when the corresponding module is uninstalled.

Please have a look and comment on it:
https://cdcidev.mtmco.net/mmoda/

@andriineronov, would you provide another html help file if you want to see how it is rendered.

**Comment by volodymyrss** [comment]
I think it's @dsavchenko who provides the html rendered from md by the bot. @andriineronov can point to which help page he may want to see updated.

However, maybe we should also leave something for the bot to do in a demonstration. We already saw that HTML we had from @andriineronov 's repo looks good in frontend.
Maybe next step is for @dsavchenko to add it to the bot.

**Comment by motame** [comment]
If happy with it, I'll push it to Github that @dsavchenko can test it.
Or should I may be create a branch for it ?

**Comment by dsavchenko** [comment]
I could convert another one manually, if prepared by @andriineronov 
But if it basically works, it's probably better to test directly with bot (it's not much left to do to finish the PR). As far as your changes merged and the container built with CI/CD I will try

**Comment by volodymyrss** [comment]
Since @motame already tested last time, and I assume also tested with Fermi the newer design, it's nicer if @dsavchenko tests with bot I think.

**Comment by andriineronov** [comment]
So I don't do anything at the moment, right?

**Comment by volodymyrss** [comment]
> So I don't do anything at the moment, right?

I do not think so. We just need you to keep preparing the .md files for your instruments at you convenience.

Conversion to HTML is done on @dsavchenko side either by manually or by bot (since this feature is close enough now).
We can just take any if those @andriineronov  wrote. Bot will convert all of them and we will see different cases.

@motame I assume you tried with Fermi, right?
If so, could you share the frontend code so that @dsavchenko can test it with https://github.com/oda-hub/oda-bot/pull/28?

**Comment by motame** [comment]
> @motame I assume you tried with Fermi, right? If so, could you share the frontend code so that @dsavchenko can test it with [oda-hub/oda-bot#28](https://github.com/oda-hub/oda-bot/pull/28)?

Yes, indeed ! 
@dsavchenko, a branch is created for it [import-md-help-page](/oda-hub/mmoda-frontend-module/tree/import-md-help-page)

**Comment by dsavchenko** [comment]
It works! The help page for Fermi is now added to staging.odahub.fr/mmoda by bot. I think we can merge the branch https://github.com/oda-hub/mmoda-frontend-module/pull/209
