### ISSUE TITLE
for logged in users, token is not sent by the frontend to run_analysis

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#207]
on production instance for logged in users, token is not sent by the frontend to run_analysis

it is correctly generated and saved in a cookie

but it is not sent

it also can not be copied in keyboard

I suspect it is some policy change at unige since it happened since yesterday **with no change to the frontend** and staging at france works

**Comment by burnout87** [comment]
I noticed it too.

Trying to understand what the cause could be

**Comment by burnout87** [comment]
it seems like, the `token` is not present where it usually is. 

Just a guess: could it be related to the PHP update you performed recently?

**Comment by volodymyrss** [comment]
I did not yet perform the update. The pod was running continuously for 183 days.

The token is present in cookies where it is set successfully on login.
It can also be seen in view token view.

Which other places you mean where it is not?

**Comment by volodymyrss** [comment]
the problem is that `Drupal.visitor.token` is set with HttpOnly and Secure options.
And this does not work with jquery like [parameters['token'] = $.cookie('Drupal.visitor.token');](https://github.com/oda-hub/mmoda-frontend-module/blob/8b95418e1428e702041026ee756231ba78cd3fdd/js/mmoda.instrument.js#L2429-L2430) because it is not meant to be

if I manually set HttpOnly to false on the cookie, all works

If I check on the same instance but internal URL, without proxy, it works:

https://frontend-prod.obsuks1.unige.ch/mmoda/

So seems like the change is introduced by proxy at UNIGE/Astro. @motame  is in contact with them and can figure out please?
I just note that it is possible to modify a cookie in this way and people [do this](https://drupal.stackexchange.com/questions/194805/setting-secure-cookies). It would be compatible with last day's tightening of security.

so I think we need @burnout87 and especially @motame  
1. confirm that this is the case (it is still possible this is something else)
2. figure out with Astro admins if indeed this proxy change was made. It might affect other sites
3. mitigate in one of the two ways:
  a.  revert likely proxy change
  b. change mmoda module to deal with new proxy setting

**Comment by burnout87** [comment]
> I did not yet perform the update. The pod was running continuously for 183 days.
> 
> The token is present in cookies where it is set successfully on login. It can also be seen in view token view.
> 
> Which other places you mean where it is not?

when preparing the formData before the submission, no token is found inside `$.cookie('Drupal.visitor.token')`:

https://github.com/oda-hub/mmoda-frontend-module/blob/8b95418e1428e702041026ee756231ba78cd3fdd/js/mmoda.instrument.js#L1041-L1044

**Comment by burnout87** [comment]
> if I manually set HttpOnly to false on the cookie, all works
> 

> 
>     1. confirm that this is the case (it is still possible this is something else)

I confirm I could make it work by changing HttpOnly (other cookies are affecteted too).

> 3. mitigate in one of the two ways:
>  a. revert likely proxy change
>  b. change mmoda module to deal with new proxy setting

I am looking into ways to make that cookie usable again, but I don't have the privileges to change the apache settings.

**Comment by motame** [comment]
Hi,
I test it right now and it seems to work :
- Requested ISGRI image, the default object and parameters
- Clicked on the button "Share"
- Entered the link in **another browser**
- The image is displayed properly (after processing of course - request to dispatcher, etc.)

**Comment by volodymyrss** [comment]
> > I did not yet perform the update. The pod was running continuously for 183 days.
> > The token is present in cookies where it is set successfully on login. It can also be seen in view token view.
> > Which other places you mean where it is not?
> 
> when preparing the formData before the submission, no token is found inside `$.cookie('Drupal.visitor.token')`:
> 
> https://github.com/oda-hub/mmoda-frontend-module/blob/8b95418e1428e702041026ee756231ba78cd3fdd/js/mmoda.instrument.js#L1041-L1044

token is there it just can not be accessed due to security settings

**Comment by motame** [comment]
ah OK OK

**Comment by volodymyrss** [comment]
> Hi, I test it right now and it seems to work :
> 
>     * Requested ISGRI image, the default object and parameters
> 
>     * Clicked on the button "Share"
> 
>     * Entered the link in **another browser**
> 
>     * The image is displayed properly (after processing of course - request to dispatcher, etc.)

default request is public and hence does not depend on token being sent.

the easiest way to make private request is to select this radio button:

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/eb8c3a96-6a93-41ab-a16c-e0b71a8cad3a)

you can also just check that every request does not pass token. request should pass token so that email can be sent etc even if the request does not need token to run.

also this "copy token" button copies "undefined".

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/07d26672-d903-4db2-b050-f59517d78f0f)

**Comment by motame** [comment]
Sorry ! I am now fully in the issue :-)
In fact, the token is explicitely set as a varibale in the cookie by MMODA module:

```php
/**
 * Implements hook_user_login().
 */
function mmoda_user_login(&$edit, $account)
{
  if (! isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset') {
    $mmoda_roles = $account->roles;
    watchdog('MMODA', 'Login - User MMODA roles :' . implode(', ', $mmoda_roles));

    if (count($mmoda_roles)) {
      $jwt = jwt_link_url();
      $alg = variable_get('jwt_link_alg', 'HS256');
      $key = variable_get('jwt_link_key', '');
      $jwt_decoded_token = JWT::decode($jwt['jwt_encoded_token'], $key, array(
        $alg
      ));
      watchdog('ODA', 'Login - Adding token Cookie: ' . print_r($jwt_decoded_token, TRUE));
      user_cookie_save([
        'token' => $jwt['jwt_encoded_token']
      ]);
      // drupal_add_http_header('Authorization', 'Bearer '.$jwt['jwt_encoded_token']);
    }
  }
}
```
We need indeed to see with the sys admins (recent change at proxy level ???) but one solution would be to set in another variable : Drupal.settings  ! a JS object (passed to the client by the server).
However, doing so we should investigate whether we introduce security issues or not.
Apparently not, as putting it in a Cookie is already clearly visible at client side.

**Comment by burnout87** [comment]
I did some investigation, and it seems like by storing the token within the `Drupal.settings` is not the safest option as it becomes part of the JavaScript on the client side.

A suggested way would be to use a callback implemented server-side that simply returns the token.
I believe that is the way the `API Token` form  actually requests the token, as we saw with @motame .

**Comment by motame** [comment]
> So seems like the change is introduced by proxy at UNIGE/Astro. @motame is in contact with them and can figure out please? I just note that it is possible to modify a cookie in this way and people [do this](https://drupal.stackexchange.com/questions/194805/setting-secure-cookies).

```
Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
```

@Volodymyr, this should be done on Apache config of the MMODA server or the proxy (astro.unige.ch) ?
If the first option, have you tried it please ?
If the second one, I'll ask sys admins if it's OK to do it on the proxy.

**Comment by volodymyrss** [comment]
> > So seems like the change is introduced by proxy at UNIGE/Astro. @motame is in contact with them and can figure out please? I just note that it is possible to modify a cookie in this way and people [do this](https://drupal.stackexchange.com/questions/194805/setting-secure-cookies).
> 
> ```
> Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
> ```
> 
> @Volodymyr, this should be done on Apache config of the MMODA server or the proxy (astro.unige.ch) ? If the first option, have you tried it please ? If the second one, I'll ask sys admins if it's OK to do it on the proxy.

Sorry I was not clear enough.
`Set-Cookie` is a response header, and this command sets HttpOnly + Secure on all cookies. I suspect this is something that WAS done by the proxy admins. If so, this was the reason for our problem. But I guess you understood this judging by the internal ticket :)
If cookie is modified by the proxy, there is little we can reasonably do to them on our side. We can make workarounds like [that one](https://github.com/oda-hub/mmoda-frontend-module/pull/208) .
But I am concerned that we will miss some cases. e.g. https://github.com/oda-hub/mmoda-frontend-module/pull/208 still misses copy-token feature.

> I did some investigation, and it seems like by storing the token within the Drupal.settings object is not a safe option as it that object is part of the JavaScript on the client side.

it would be similar in security to what we get from using non-httponly cookie, right? So what we had before.
New endpoint option is nice, but then it still can be called by any client-side JS, no?

**Comment by volodymyrss** [comment]
Any news @motame @burnout87 ? I did not see any update from admins but maybe you discussed with them elsewhere.
This is quite critical for us, people are waiting.

**Comment by burnout87** [comment]
> But I am concerned that we will miss some cases. e.g. https://github.com/oda-hub/mmoda-frontend-module/pull/208 still misses copy-token feature.

with the last commits I take care also of those use-cases

>  New endpoint option is nice, but then it still can be called by any client-side JS, no?

a token is returned if the user is logged in, otherwise an empty object i returned...does it answer you question?

**Comment by volodymyrss** [comment]
As you might have seen, it was indeed the proxy change, it was found and reversed by the admins.

We might want to keep this issue and also #208 to figure out if we still want to transition to httponly cookies.

We need to be sure that:

1. all drupal versions we use are compatible with httponly cookies
2. all the developments and @motame , @burnout87  and @dsavchenko can be made to work with httponly cookies

If there is any blocking and difficult-to-address component, we need to know.

Can you investigate your respective parts?

**Comment by burnout87** [comment]
As far as for the development I have done for the frontend. #208 make it possible to avoid using cookie for the token completely.

But that is the only cookie I dealt with, there might be others we currently use.
