### ISSUE TITLE
Results panel lands in the wrong tab

### ISSUE THREAD

**Issue by burnout87** [oda-hub/mmoda-frontend-module#222]
I noticed how sometimes, if the log panel is closed soon before the completion of a request, this completes anyway.

The result panel is also created in the open instrument tab (which of course can be one different from the initial one).

Noticed in https://github.com/oda-hub/mmoda-frontend-module/issues/219#issuecomment-1863241589

**Comment by motame** [comment]
Ah OK ! that may explain exactly what is happening the issue #219

**Comment by burnout87** [comment]
mmmm I think it's a different type of issue, unless I am missing something, I don't think this is the root cause of #219 ...

**Comment by motame** [comment]
The first screenshot posted by @volodymyrss may correspond exactly to such a situation.
The reported error concerns a request canceled in ISGRI panel while he was in JEMX panel.

**Comment by burnout87** [comment]
I tried to reproduce #219 but yet I could not, despite taking into account also this bug

**Comment by volodymyrss** [comment]
> The first screenshot posted by @volodymyrss may correspond exactly to such a situation. The reported error concerns a request canceled in ISGRI panel while he was in JEMX panel.

Unfortunately it is not, because the request was sent to dispatcher with `instrument=isgri`  and `product=jemx_image` - hence the failure.

**Comment by motame** [comment]
@volodymyrss, would you tell please how to reproduce it ?

**Comment by volodymyrss** [comment]
> @volodymyrss, would you tell please how to reproduce it ?

What lead to the issue is installing new version from scratch, as delivered. Then, trying to make the default jemx request.

I will make available frontend staging so we can all view it.

But to look closer into the any issues during bootstraping, it still could be useful you try to create a new instance from scratch from the code provided, and see if it starts too.

**Comment by motame** [comment]
OK, I'll do that !

**Comment by motame** [comment]
Fixed !
Code pushed to GitHub with other consistent components, [mmoda-frontend-drupal](https://github.com/oda-hub/mmoda-frontend-drupal), [mmoda-frontend-db](https://github.com/oda-hub/mmoda-frontend-db) and [mmoda-frontend-theme](https://github.com/oda-hub/mmoda-frontend-theme)

**Comment by volodymyrss** [comment]
![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/7b37c40b-9c01-4855-968d-ebfd36bf9e65)

**Comment by dsavchenko** [comment]
> it's the latest frontend version, right?

Yes, the one you built 2 days ago

**Comment by volodymyrss** [comment]
> > it's the latest frontend version, right?
> 
> Yes, the one you built 2 days ago

So this still can happen, @motame ?

Notice that Gaia tab was open behind the modal, it's visible on the screenshot.
But the instument is sent with mismatching product.

**Comment by volodymyrss** [comment]
@motame do you see this?

**Comment by motame** [comment]
> I am seeing this again on staging:
> 
> ![image](https://private-user-images.githubusercontent.com/3909535/309320084-7b37c40b-9c01-4855-968d-ebfd36bf9e65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTUxMjUsIm5iZiI6MTcxMDE1NDgyNSwicGF0aCI6Ii8zOTA5NTM1LzMwOTMyMDA4NC03YjM3YzQwYi05YzAxLTQ4NTUtOTY4ZC1lYmZkMzZiZjllNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMTEwMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQxMTUyODcwZjkyMGIyMjIxMDRlMTlmZTBmMjg4YjM0ZGNkY2Y2ZTE3ZmI1Y2M0MGZkM2Q2NzBhMWRhNTQzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u6_94TWgacv8tiEq0a11Z8xZEcldDIllJt4_coFCAtg)
> 
> @dsavchenko , it's the latest frontend version, right?

May I have the link of this instance ?

**Comment by motame** [comment]
This is not a landing product in the wrong tab.
It's an inconsistent request : bad query parameters 
In this case, sending SPI ACS params in the query while the active instrument/tab is GAIA !

**Comment by motame** [comment]
@volodymyrss, would you please confirm whether it's via URL or when interacting directly with MMODA ?
I must say that i did not have a look when request is done via URL.

**Comment by burnout87** [comment]
can be closed has it has been fixed
