### ISSUE TITLE
Token is not included in the request when query_status is "submitted"

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/mmoda-frontend-module#224]
I see this behaviour in the master branch of frontend-module, at least with the nb2workflow-based instrument.

The behaviour is as follows:
1. First, the GET request for `get_token` is done
2. POST request to `run_analysis` contains `query_status="new"` and the token in the form data as expected and is successful, `job_status="submitted"` and `query_status="submitted"` is in the response.
3. The form data of the next POST now has `query_status="submitted"` set, but there is no token there. This obviously leads to 403, "Request not authorized" from dispatcher.

**Comment by burnout87** [comment]
ok I think I know where the error is, and what is missing, thanks for reporting it I had missed to adjust a call

**Comment by burnout87** [comment]
I suspect, it has to do with #218

**Comment by dsavchenko** [comment]
Ah, OK, so this one is actually a duplicate. I didn't notice (or just forgot) the https://github.com/oda-hub/mmoda-frontend-module/issues/218
