### ISSUE TITLE
make sure that progress reports are allways shown

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#227]
possibly "more" button is currently specific to jemx/isgri

**Comment by burnout87** [comment]
the progress report is build if the in the object returned by the dispatcher there is a not-empty entry `full_report_dict_list`, and this will be used to build the table in the following function:

https://github.com/oda-hub/mmoda-frontend-module/blob/15c8f38c953c6281adcafc778d52e8f6519201bf/js/mmoda.instrument.js#L316-L397

**Comment by volodymyrss** [comment]
> the progress report is build if the in the object returned by the dispatcher there is a not-empty entry `full_report_dict_list`, and this will be used to build the table in the following function:
> 
> https://github.com/oda-hub/mmoda-frontend-module/blob/15c8f38c953c6281adcafc778d52e8f6519201bf/js/mmoda.instrument.js#L316-L397

it's possible that `data_units` is empty and it returns empty even if `full_report_dict_list` is full.

**Comment by burnout87** [comment]
`data_units` is the content of the entry `input_prod_list` from the obj returned by the dispatcher

**Comment by volodymyrss** [comment]
> `data_units` is the content of the entry `input_prod_list` from the obj returned by the dispatcher

so does it appear empty in other instruments than ISGRI/JEMX?

**Comment by burnout87** [comment]
> 
> so does it appear empty in other instruments than ISGRI/JEMX?

and in that case only the status update is visualized. eg `2024.01.24T19:13:22 Status : submitted`

**Comment by volodymyrss** [comment]
> > so does it appear empty in other instruments than ISGRI/JEMX?
> 
> and in that case only the status update is visualized. eg `2024.01.24T19:13:22 Status : submitted`

We can separate part which lists full_report_dict_list messages from the part which draws table. Draw table when there are input_products, but list messages if there is full_report_dict_list.

**Comment by burnout87** [comment]
> 
> We can separate part which lists full_report_dict_list messages from the part which draws table. Draw table when there are input_products, but list messages if there is full_report_dict_list.

Both for `full_report_dict_list` and `input_prod_list` a table is drawn, with the difference that the content of `full_report_dict_list` is used for the visualization of the content of  `input_prod_list`. So they're not really separable...

**Comment by volodymyrss** [comment]
> > We can separate part which lists full_report_dict_list messages from the part which draws table. Draw table when there are input_products, but list messages if there is full_report_dict_list.
> 
> Both for `full_report_dict_list` and `input_prod_list` a table is drawn, with the difference that the content of `full_report_dict_list` is also used for the visualization of the content of `input_prod_list`. So they're not really separable...

`full_report_dict_list`  is also "visualized" in a way which is independent of `input_prod_list`, in a set of lines. Isn't it?
