### ISSUE TITLE
when no values are given to RA/Dec they are still green

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#231]

**Comment by burnout87** [comment]
So I just checked the code and it seems like that this is intentional. Maybe there was a reason for allowing empty RA and DEC values?

https://github.com/oda-hub/mmoda-frontend-module/blob/0c4b99ce50b8e870f1b6a0e472bb149ba21f4f0c/js/mmoda.common.js#L75-L79

https://github.com/oda-hub/mmoda-frontend-module/blob/0c4b99ce50b8e870f1b6a0e472bb149ba21f4f0c/js/mmoda.common.js#L130-L134

**Comment by volodymyrss** [comment]
It could be, but then they should not be marked as required with the stars.

**Comment by burnout87** [comment]
that's easy to adapt, the validation makes sure the format is correct and also the value provided

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/5320f2e3-7491-4682-bb78-5124adb8e163)

**Comment by volodymyrss** [comment]
> that's easy to adapt, the validation only makes sure the format is correct and also the value provided
> 
> ![image](https://private-user-images.githubusercontent.com/3757833/312149448-5320f2e3-7491-4682-bb78-5124adb8e163.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTk2ODYsIm5iZiI6MTcxMDI1OTM4NiwicGF0aCI6Ii8zNzU3ODMzLzMxMjE0OTQ0OC01MzIwZjJlMy03NDkxLTQ2ODItYmI3OC01MTI0YWRiOGUxNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTYwMzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjEyZTY5MjQwZTY2ZmFhZjFiNjM3YWI3MjI5NmRlZWVlZDNjNWI5NTQ1NTE0MGJmNjdhMzU3MjQzNGY3N2NjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZBwNTYrUmriDCugHS2T9sv6MAMjamLxrcoe-EDdfOmM)

Either format and range is correct or it is not provided, right?

**Comment by burnout87** [comment]
> Either format and range is correct or it is not provided, right?

yes, same for DEC
