### ISSUE TITLE
 “contact us” doesn’t work on Safari, but does on Chrome.

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#234]
https://www.astro.unige.ch/mmoda/node/383/submission/147

**Comment by burnout87** [comment]
just tried from safari  using the mac mini just setup in my office, and it seems to be working

https://www.astro.unige.ch/mmoda/node/383/submission/150

**Comment by burnout87** [comment]
also the write feedback button

https://www.astro.unige.ch/mmoda/node/392/submission/151

**Comment by volodymyrss** [comment]
Maybe reach out to the user, ask for more details? Contact info should be in the original request.

**Comment by burnout87** [comment]
Just tried on another Ssafari, at the latest version (17.3.1), and actually the form is not working:

<img width="1320" alt="image" src="https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/32f7fae5-bad7-4273-a6f5-4611dfff3b17">


@motame any ideas?

**Comment by motame** [comment]
It's happening in the script misc/ajax.js :

```Javascript
    // Bind the ajaxSubmit function to the element event.
    $(ajax.element).bind(element_settings.event, function(event) {
      if (!Drupal.settings.urlIsAjaxTrusted[ajax.url] && !Drupal.urlIsLocal(ajax.url)) {
        throw new Error(Drupal.t('The callback URL is not local and not trusted: !url', { '!url': ajax.url }));
      }
      return ajax.eventResponse(this, event);
    });
```
The url 'modal_forms/ajax/webform/383' is local and Drupal.urlIsLocal(ajax.url) should return true.
Why is it apparently returning false on Safari ??
I can not test it !
@burnout87, could you check that value please ?

**Comment by burnout87** [comment]
tried to debug a bit further

<img width="1202" alt="image" src="https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/71ea2104-574d-4446-86fe-c0a27afc2cba">


it seems like `ajax.url` (which is "modal_forms/ajax/webform/383") is not ajaxTruested, which I don't really know what that means, and also is not local `Drupal.urlIsLocal` returns false

**Comment by burnout87** [comment]
Tested even more, and I got the same issue also on Chrome (both Mac and Ubuntu) and Firefox

I then tested the local instance and :

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/65e32e1e-c8ec-4648-807a-4a046b5c0a98)

Same for the staging

**Comment by burnout87** [comment]
We did some more testing on the production instance with @motame and verified that sometimes this works, and sometimes it does not. For me, it never regardless of the browser (tried also to clean the cache and delete all the cookies).

For @motame , it was always the opposite, always working.

Whereas for the staging instance or my local one, the issue never appears

**Comment by burnout87** [comment]
UPDATE after having deleted all the cookies, it worked. It's really unpredictable

**Comment by burnout87** [comment]
After some more testing, we figured out that the issue appears if the trailing slash is not present:
* [[http](https://www.astro.unige.ch/mmoda)](https://www.astro.unige.ch/mmoda) -> contact us form does not work
* [https://www.astro.unige.ch/mmoda/](https://www.astro.unige.ch/mmoda/) -> contact us form does work

**Comment by volodymyrss** [comment]
ok then it can be considered resolved. unless it reappears when passed through extra proxy in prod unige.

**Comment by volodymyrss** [comment]
thanks!
