### ISSUE TITLE
Waiting dialog is no more showing the help pages properly

### ISSUE THREAD

**Issue by motame** [oda-hub/mmoda-frontend-module#238]
Following the improvements introduced by the issue #223, the help pages are no more shown.
The help pages are displayed with the same modal panel, waintingDialog object, as the request processing progress.

The problem is in the function "show" of waitingDialog (function get_waitingDialog in mmoda.common.js).
The second parameter "message" containing the content of the help page is no more displayed.

The display of help pages is handled by the processing of the event 'click' on the class 'open-in-modal':
```javascript
    $('body').on('click', '.open-in-modal', function(e) {
      e.preventDefault();
      ...
      waitingDialog.show(home_link + title, help_text, {
          dialogSize: 'lg',
          buttonText: 'Close',
          showCloseInHeader: true,
        });
     ...
```
@burnout87, could you have a look ...

**Comment by burnout87** [comment]
Thanks @motame , minor improvements were needed to the `show` function:

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/22ebc994-e87d-4c46-b4df-b8ac26138e75)
