### ISSUE TITLE
new frontend does not show ODA events for me

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#245]
@dsavchenko can you add oda events which appear as announcements on your staging.odahub.fr?

**Comment by dsavchenko** [comment]
I never considered adding it, so I don't really know how

**Comment by volodymyrss** [comment]
Here is how:

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/1506a226-9343-4c82-9ac5-65954281b9a4)

Important to set this field:

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/8d9f54e8-a14f-4b66-a6fc-57150a2ef665)

Could you check if it works for you?

**Comment by motame** [comment]
I'm taking care of this issue ...

**Comment by dsavchenko** [comment]
> Could you check if it works for you?

Doesn't work for me on French staging

**Comment by motame** [comment]
ODA events are now shown.

![chrome_jqiaY7MUuX](https://github.com/oda-hub/mmoda-frontend-module/assets/44972498/d8ce60a8-4e83-49cd-82b2-7d2bba7b74dc)

**Comment by volodymyrss** [comment]
Thanks @motame ! So it was something in the config? Could you please explain so we add it to the deployment?

**Comment by motame** [comment]
Absolutely !
The corresponding view block was hidden.

![wqNsRNP1EV](https://github.com/oda-hub/mmoda-frontend-module/assets/44972498/51eeb6c7-c705-4714-a0c2-2606201fc366)

**Comment by volodymyrss** [comment]
Ok thanks, so the change will be committed to the DB?

By the way, looks like something is weird upon clicking on the link:

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/bbde756e-acc0-48de-8594-7c3c8d211a58)

**Comment by motame** [comment]
Absolutely, I've seen it.
It's may be a side effect of the changes introduced on the dialog window (Javascript).
@burnout87, could you please have a look ...

**Comment by motame** [comment]
Here was the config of that block...

![zv1w6GxlFQ](https://github.com/oda-hub/mmoda-frontend-module/assets/44972498/532d7dec-24ca-4ba0-926b-4bd60e37f08e)

**Comment by motame** [comment]
> Ok thanks, so the change will be committed to the DB?
> 

Absolutely !

**Comment by burnout87** [comment]
> Absolutely, I've seen it. It's may be a side effect of the changes introduced on the dialog window (Javascript). @burnout87, could you please have a look ...

Indeed it is...and probably the fix is simple

**Comment by burnout87** [comment]
Can also the "1 of 1" page number be easily removed from the block ?

**Comment by motame** [comment]
> Can also the "1 of 1" page number be easily removed from the block ?

It's in fact a slideshow and it could be useful to show that there is more than one event/news.

**Comment by motame** [comment]
> Absolutely, I've seen it. It's may be a side effect of the changes introduced on the dialog window (Javascript). @burnout87, could you please have a look ...

Indeed the fix of #248 fixed it !
