### ISSUE TITLE
where to set frontend version?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#264]
![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/68e60706-6cff-41c2-8d26-8d37ae6e7be2)

**Comment by burnout87** [comment]
related to #263

**Comment by burnout87** [comment]
to set the version, this should be inserted in the file `mmoda.info`

https://github.com/oda-hub/mmoda-frontend-module/blob/db9a0c994a91f48091851281e30944e7d2473d7f/mmoda.info#L4

the module needs anyway re-installation, to remove the error currently visible too

**Comment by volodymyrss** [comment]
> to set the version, this should be inserted in the file `mmoda.info`
> 
> https://github.com/oda-hub/mmoda-frontend-module/blob/db9a0c994a91f48091851281e30944e7d2473d7f/mmoda.info#L4
> 
> the module needs anyway re-installation, to remove the error currently visible too

so but isn't it included in the deployment?

**Comment by burnout87** [comment]
once the version is set inside the info file, this will be queried from the DB from the following function:

https://github.com/oda-hub/mmoda-frontend-module/blob/db9a0c994a91f48091851281e30944e7d2473d7f/mmoda.lib.inc#L435C20-L453C1

**Comment by volodymyrss** [comment]
> once the version is set inside the info file,

But it's set, right?

> this will be queried from the DB from the following function:
> 
> https://github.com/oda-hub/mmoda-frontend-module/blob/db9a0c994a91f48091851281e30944e7d2473d7f/mmoda.lib.inc#L435C20-L453C1
> 
> with the installation of the module, the version is automatically inserted inside the DB

The module is reinstalled nightly. So it should be installed?

**Comment by burnout87** [comment]
> > once the version is set inside the info file,
> 
> But it's set, right?

yes it is
> 
> > this will be queried from the DB from the following function:
> > https://github.com/oda-hub/mmoda-frontend-module/blob/db9a0c994a91f48091851281e30944e7d2473d7f/mmoda.lib.inc#L435C20-L453C1
> > with the installation of the module, the version is automatically inserted inside the DB
> 
> The module is reinstalled nightly. So it should be installed?

ok, then I don't understand why we have that error, it looks like it doesn't read the DB...

**Comment by volodymyrss** [comment]
do you know what could be the reason the error is still there?

**Comment by burnout87** [comment]
it's really strange, @dsavchenko did you have to do anything after the [commit](https://github.com/oda-hub/mmoda-frontend-module/commit/350ac3cbf7240a8b5599bc21b05151a995f0076d) was pushed ?

**Comment by dsavchenko** [comment]
Normally, it should be reinstalled automatically in init container. But something may go wrong when starting from problematic state

**Comment by burnout87** [comment]
I see that on the unige instance the version is properly set and the error disappeared.

Which action applied the fix ?

**Comment by volodymyrss** [comment]
Nothing was done, it just changed after one of the builds. Oh well.
