### ISSUE TITLE
Please split the project into issues and estimate load

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#268]
@ferrigno , @volodymyrss , @dsavchenko  to be aware

**Comment by motame** [comment]
The three main remaining tasks are : 

1. Implementation of the tab instrument generator
2. Export/import of the help page content type and help page nodes
3. Datatables Editor used for the edition of the catalogs (acquire the new version of the library and update JS code to use it)

After a discussion with Gabrielle, we come up to the fact that he may take care of the first task and I take care of the two others.
We should create soon GitHub issues with the estimated load.

**Comment by volodymyrss** [comment]
Ok, thank you, please split further and estimate.

**Comment by volodymyrss** [comment]
Thank you! Let's also set some estimates in full-time days, @motame @burnout87 .
