### ISSUE TITLE
When opening a link from the email, `filters_table` should be properly parsed and the form filled

### ISSUE THREAD

**Issue by burnout87** [oda-hub/mmoda-frontend-module#276]

**Comment by volodymyrss** [comment]
could you please paste the link here?

**Comment by burnout87** [comment]
https://staging.odahub.fr/mmoda//dispatch-data/resolve-job-url?job_id=db8065555312ff65&session_id=ECH6G7DW0PROGDTF&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJjby50dWNjaUB1bmlnZS5jaCIsImVtYWlsIjoibWFyY28udHVjY2lAdW5pZ2UuY2giLCJuYW1lIjoibWF0dWNjaTcyIiwicm9sZXMiOiJhdXRoZW50aWNhdGVkIHVzZXIsIG9kYSB3b3JrZmxvdyBkZXZlbG9wZXIiLCJleHAiOjE3Mjk2OTcyMDh9.upxL9e_31KJEa6MGnhNYKx_6l8cZpQWAoNUUl0BBEBo

**Comment by burnout87** [comment]
![image](https://github.com/user-attachments/assets/9487926e-f435-4c70-bcd0-9f423e54047f)

Now the filters are properly filled up starting from the URL. 

To keep in mind, that the fits file is not re-requested (using its URL), as it might add a bit of overhead, if needed we can add it in the future. But for this specific use-case, probably it will not be necessary
