### ISSUE TITLE
Transport type for E-mail delivery

### ISSUE THREAD

**Issue by motame** [oda-hub/mmoda-frontend-module#92]
We need to decide about the transport type for email delivery as it is shown on the Email delivery page of Drupal:
- SMTP
- sendmail
- PHP

![firefox_fwWeJcBzAT](https://user-images.githubusercontent.com/44972498/136177937-5805c707-f725-4044-8874-705894bbc4dd.png)

May be @volodymyrss you know the better option for deployment ??

**Comment by motame** [comment]
I see what you mean !
I agree that it's a deployment issue but  I thought that it can be simplified if it's the same.
I'll do it then later ...
I keep using PHP or sendmail which are already configured on my dev machine.

**Comment by volodymyrss** [comment]
ok! the problem is only that it is not entirely smooth now with HTML emails. Should we do anything about this or revert to what seemed to have worked?

**Comment by volodymyrss** [comment]
or maybe it works now. Need to test more.

**Comment by motame** [comment]
Have you deployed the latest db dump ?

**Comment by motame** [comment]
It seems not !
As the module mimemail is hown as installed !!!

![uTmT53MoWe](https://user-images.githubusercontent.com/44972498/136198986-6386bc98-3252-43f5-bb01-505f88606474.png)
