### ISSUE TITLE
if URL does not properly lead to a request, there should be a warning

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#98]
we had this before, but also here: https://github.com/oda-hub/dispatcher-app/issues/265
the URL effectively leads to the front page with some values substituted. User is unsure what happens. In fact, there was an issue on frontend, not all values were set, and and "submit" did not happen. There should be an alert in this case.

**Comment by motame** [comment]
Fixed !
The form was filled by whatever parameter provided in the url.
The mmoda client was completely relying on the back-end for the request processing.

This seems OK for all types of HTML inputs except the input type "file" which can not be set using JavaScript which is normal.
JS can not decide to attach a local file to the request (basic security issue).
Now, this type is excluded during this form filling step.
If a file name is provided in the url a clear warning is shown.
In addition to that each form input is filled within a try-catch section to track all possible errors during this step.
If any error raises an error is displayed in a modal window.

![firefox_4aR5U2uZeZ](https://user-images.githubusercontent.com/44972498/152771896-c9dffb55-e1b9-44c2-b72e-8af98f375a30.png)

As discussed during the last meeting, we should whether to block the request sharing when it does include a user catalog.

**Comment by volodymyrss** [comment]
Sounds good!

For the message, I would suggest

```
Unfortunately, the URL you used to access this page contains parameter combination which could not be interpreted.

You probably need another URL. 

If you are not sure how to obtain it, please feel free to contact us using the "Write feedback" form below.

This further information may help:

* file paramter ....

```

**Comment by motame** [comment]
Currently, the error message is also reporting the form error messages in an HTML list :
`The entered url is not valid : <ul><li>' + make_request_error_messages.join('</li><li>') + '</li></ul>`
It's not limited to file parameter only.

Given your input Volodymyr, it can be reported as :
```
'<p>Unfortunately, the URL you used to access this page contains parameter combination which could not be interpreted.</p>'
+ 'Errors : <ul><li>' + make_request_error_messages.join('</li><li>') + '</li></ul>'
+'<p>You probably need another URL. </p>'
+'<p>If you are not sure how to obtain it, please feel free to contact us using the "Write feedback" form below.</p>'
```

make_request_error_messages is an array of all form error messages.
The info about the file parameter should appear in the list of errors.

**Comment by volodymyrss** [comment]
Sounds good! So it is possible to try on your dev?

**Comment by motame** [comment]
Implemented on dev !
Can be tried with this url :
https://cdcidev.mtmco.net/mmoda/?DEC=-30.361277777778&E1_keV=20&E2_keV=40&RA=275.91904166667&T1=2017-03-06T13%3A26%3A48.0&T2=2017-03-06T15%3A32%3A27.0&T_format=isot&detection_threshold=5&instrument=isgri&integral_data_rights=all-private&max_pointings=50&osa_version=OSA11.1&product_type=isgri_lc&query_status=new&query_type=Real&radius=15&scw_list=242300320010.000%2C242300330010.000%2C242300420010.000%2C242300430010.000%2C242300520010.000&src_name=4U+1820-30&time_bin=20.5&time_bin_format=sec&use_scws=form_list&user_catalog_file=%2Ftmp%2Ftmpfoz0xq4d_sid_URRZMHBY6HNPU2IO%2F4U1820_ODA_cat.fits

**Comment by volodymyrss** [comment]
Ok!

Will it also report wrong fields, or incompatible field types?

E.g. (DC instead of DEC) :

https://cdcidev.mtmco.net/mmoda/?DC=-30.361277777778&E1_keV=20&E2_keV=40&RA=275.91904166667&T1=2017-03-06T13%3A26%3A48.0&T2=2017-03-06T15%3A32%3A27.0&T_format=isot&detection_threshold=5&instrument=isgri&integral_data_rights=all-private&max_pointings=50&osa_version=OSA11.1&product_type=isgri_lc&query_status=new&query_type=Real&radius=15&scw_list=242300320010.000%2C242300330010.000%2C242300420010.000%2C242300430010.000%2C242300520010.000&src_name=4U+1820-30&time_bin=20.5&time_bin_format=sec&use_scws=form_list

Or (DEC=notafloat)

https://cdcidev.mtmco.net/mmoda/?DEC=notafloat&E1_keV=20&E2_keV=40&RA=275.91904166667&T1=2017-03-06T13%3A26%3A48.0&T2=2017-03-06T15%3A32%3A27.0&T_format=isot&detection_threshold=5&instrument=isgri&integral_data_rights=all-private&max_pointings=50&osa_version=OSA11.1&product_type=isgri_lc&query_status=new&query_type=Real&radius=15&scw_list=242300320010.000%2C242300330010.000%2C242300420010.000%2C242300430010.000%2C242300520010.000&src_name=4U+1820-30&time_bin=20.5&time_bin_format=sec&use_scws=form_list

It does not show an error.

**Comment by motame** [comment]
Indeed, it's not checking that.
It's delegated to the back-end.
And the latter reports :
`Error 400, Bad Request: [ InstrumentQueryBackEnd : isgri ] constructor failed: Invalid character at col 0 in angle 'notafloat'`

**Comment by motame** [comment]
Let me investigate more ...
As it should do ...

**Comment by motame** [comment]
The mentioned errors (unknown parameters or parameter bad values) are now processed at the front-end level.

**Comment by volodymyrss** [comment]
Ok, thanks, looks good!

But, I find that the URLs open ~50% of the time - like with IBAS.

**Comment by volodymyrss** [comment]
I  think this is done. Will re-open if it reoccurs.
